import type {
  School,
  Vendor,
  StudentProfile,
  Application,
  InterviewTicket,
  VaultDocument,
  FormCatalogItem,
  Transaction,
  UserAccount,
  ParentGamification,
  Notification,
  AcademicYear,
  GradingScale,
} from '@/types';

// ── Schools ───────────────────────────────────────────────────────────────────

export const schools: School[] = [
  {
    id: 'sch_001',
    name: 'Delhi Public School',
    code: 'DPS-DEL',
    boardType: 'CBSE',
    address: 'Sector 12, R.K. Puram',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '+91-11-2655-0000',
    email: 'admissions@dps.delhi.edu',
    website: 'https://dps.delhi.edu',
    feesRange: { min: 65000, max: 120000 },
    facilities: ['Smart Classrooms', 'Science Labs', 'Library', 'Sports Complex', 'Swimming Pool', 'Auditorium'],
    capacity: 3000,
    availableSeats: 150,
    description: 'One of the most prestigious CBSE schools in Delhi with excellent academic track record and state-of-the-art facilities.',
    logo: '/school-1.png',
    rating: 4.8,
    alumniCount: 25000,
    foundedYear: 1972,
    demandLevel: 'high',
    image: '/school-1.png',
  },
  {
    id: 'sch_002',
    name: "St. Xavier's Academy",
    code: 'SXA-MUM',
    boardType: 'ICSE',
    address: '45, Marine Lines',
    city: 'Mumbai',
    state: 'Maharashtra',
    phone: '+91-22-2200-1234',
    email: 'info@stxaviers.academy',
    website: 'https://stxaviers.academy',
    feesRange: { min: 80000, max: 150000 },
    facilities: ['Smart Classrooms', 'Computer Labs', 'Library', 'Football Ground', 'Basketball Court', 'Music Room'],
    capacity: 2000,
    availableSeats: 80,
    description: 'Premier ICSE institution in Mumbai known for holistic education and strong emphasis on sports and arts.',
    logo: '/school-2.png',
    rating: 4.7,
    alumniCount: 18000,
    foundedYear: 1869,
    demandLevel: 'high',
    image: '/school-2.png',
  },
  {
    id: 'sch_003',
    name: 'Greenwood International',
    code: 'GWI-BLR',
    boardType: 'IB',
    address: 'Whitefield Main Road',
    city: 'Bangalore',
    state: 'Karnataka',
    phone: '+91-80-2847-5000',
    email: 'admissions@greenwoodintl.edu',
    website: 'https://greenwoodintl.edu',
    feesRange: { min: 200000, max: 350000 },
    facilities: ['IB Lab', 'Robotics Lab', 'Swimming Pool', 'Tennis Courts', 'Theatre', 'Design Studio'],
    capacity: 1200,
    availableSeats: 45,
    description: 'Top-tier IB World School offering PYP, MYP and DP programmes with world-class infrastructure.',
    logo: '/school-3.png',
    rating: 4.9,
    alumniCount: 5000,
    foundedYear: 2003,
    demandLevel: 'medium',
    image: '/school-3.png',
  },
  {
    id: 'sch_004',
    name: 'City Montessori School',
    code: 'CMS-LKO',
    boardType: 'CBSE',
    address: 'Gomti Nagar, Lucknow',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    phone: '+91-522-230-0000',
    email: 'cms@cms.education',
    website: 'https://cms.education',
    feesRange: { min: 40000, max: 70000 },
    facilities: ['Digital Classrooms', 'Science Park', 'Library', 'Playground', 'Art Room', 'Dance Studio'],
    capacity: 2500,
    availableSeats: 200,
    description: 'One of the largest city schools with affordable quality education and strong cultural values.',
    logo: '/school-4.png',
    rating: 4.5,
    alumniCount: 30000,
    foundedYear: 1959,
    demandLevel: 'high',
    image: '/school-4.png',
  },
  {
    id: 'sch_005',
    name: 'The Heritage School',
    code: 'THS-KOL',
    boardType: 'State',
    address: 'Salt Lake, Sector V',
    city: 'Kolkata',
    state: 'West Bengal',
    phone: '+91-33-2357-8900',
    email: 'admissions@heritageschool.kolkata',
    website: 'https://heritageschool.kolkata',
    feesRange: { min: 35000, max: 55000 },
    facilities: ['Classrooms', 'Labs', 'Library', 'Sports Ground', 'Computer Lab'],
    capacity: 1500,
    availableSeats: 120,
    description: 'Heritage school blending traditional values with modern education at affordable fees.',
    logo: '/school-5.png',
    rating: 4.3,
    alumniCount: 12000,
    foundedYear: 1995,
    demandLevel: 'medium',
    image: '/school-5.png',
  },
  {
    id: 'sch_006',
    name: 'Podar International',
    code: 'POD-PUN',
    boardType: 'CBSE+IB',
    address: 'Kalyani Nagar, Pune',
    city: 'Pune',
    state: 'Maharashtra',
    phone: '+91-20-2663-0100',
    email: 'pune@podar.org',
    website: 'https://podar.org/pune',
    feesRange: { min: 90000, max: 180000 },
    facilities: ['Smart Boards', 'STEM Lab', 'Library', 'Swimming Pool', 'Skating Rink', 'Amphitheatre'],
    capacity: 1800,
    availableSeats: 90,
    description: 'Leading CBSE+IB school with focus on experiential learning and global exposure.',
    logo: '/school-6.png',
    rating: 4.6,
    alumniCount: 15000,
    foundedYear: 1927,
    demandLevel: 'high',
    image: '/school-6.png',
  },
  {
    id: 'sch_007',
    name: 'Saraswati Vidya Mandir',
    code: 'SVM-CHN',
    boardType: 'State',
    address: 'Adyar, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91-44-2498-7000',
    email: 'contact@svm.chennai.edu',
    website: 'https://svm.chennai.edu',
    feesRange: { min: 25000, max: 45000 },
    facilities: ['Digital Classrooms', 'Labs', 'Library', 'Playground'],
    capacity: 1000,
    availableSeats: 80,
    description: 'State board school with strong Tamil cultural foundation and academic excellence.',
    rating: 4.2,
    alumniCount: 8000,
    foundedYear: 1985,
    demandLevel: 'low',
  },
  {
    id: 'sch_008',
    name: 'Global International School',
    code: 'GIS-HYD',
    boardType: 'IB',
    address: 'Banjara Hills, Hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    phone: '+91-40-2335-4400',
    email: 'info@globalintl.hyd',
    website: 'https://globalintl.hyd',
    feesRange: { min: 150000, max: 280000 },
    facilities: ['Smart Classrooms', 'Innovation Lab', 'Library', 'Swimming Pool', 'Horse Riding', 'Golf'],
    capacity: 800,
    availableSeats: 30,
    description: 'Exclusive IB school with premium facilities and personalized learning approach.',
    rating: 4.8,
    alumniCount: 3000,
    foundedYear: 2010,
    demandLevel: 'critical',
  },
];

// ── Vendors ───────────────────────────────────────────────────────────────────

export const vendors: Vendor[] = [
  {
    id: 'ven_001',
    vendorId: 'VEN001',
    name: 'Ramesh Kumar',
    email: 'ramesh@vendor.eduresult',
    phone: '+91-98765-43210',
    status: 'active',
    tokenBalance: 1240,
    totalCollections: 485000,
    totalTicketsPrinted: 1250,
    performanceScore: 4.8,
    joinDate: '2024-03-15',
    location: 'New Delhi',
  },
  {
    id: 'ven_002',
    vendorId: 'VEN002',
    name: 'Suresh Patel',
    email: 'suresh@vendor.eduresult',
    phone: '+91-98765-43211',
    status: 'active',
    tokenBalance: 890,
    totalCollections: 320000,
    totalTicketsPrinted: 890,
    performanceScore: 4.5,
    joinDate: '2024-04-20',
    location: 'Mumbai',
  },
  {
    id: 'ven_003',
    vendorId: 'VEN003',
    name: 'Priya Sharma',
    email: 'priya@vendor.eduresult',
    phone: '+91-98765-43212',
    status: 'active',
    tokenBalance: 1560,
    totalCollections: 620000,
    totalTicketsPrinted: 1780,
    performanceScore: 4.9,
    joinDate: '2024-01-10',
    location: 'Bangalore',
  },
  {
    id: 'ven_004',
    vendorId: 'VEN004',
    name: 'Amit Singh',
    email: 'amit@vendor.eduresult',
    phone: '+91-98765-43213',
    status: 'suspended',
    tokenBalance: 120,
    totalCollections: 95000,
    totalTicketsPrinted: 320,
    performanceScore: 3.2,
    joinDate: '2024-06-01',
    location: 'Lucknow',
  },
  {
    id: 'ven_005',
    vendorId: 'VEN005',
    name: 'Deepa Reddy',
    email: 'deepa@vendor.eduresult',
    phone: '+91-98765-43214',
    status: 'active',
    tokenBalance: 2100,
    totalCollections: 780000,
    totalTicketsPrinted: 2100,
    performanceScore: 4.7,
    joinDate: '2023-11-25',
    location: 'Hyderabad',
  },
];

// ── Student Profiles ──────────────────────────────────────────────────────────

export const studentProfiles: StudentProfile[] = [
  {
    id: 'stu_001',
    universalStudentId: 'ERP-2025-000001',
    firstName: 'Aarav',
    lastName: 'Sharma',
    dateOfBirth: '2015-03-12',
    gender: 'male',
    bloodGroup: 'O+',
    address: '12, Patel Nagar',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110008',
    parentName: 'Rajesh Sharma',
    parentPhone: '+91-98100-11111',
    parentEmail: 'rajesh.sharma@gmail.com',
    parentRelation: 'Father',
    emergencyContact: '+91-98100-22222',
    previousSchool: 'Little Angels School',
    previousClass: 'UKG',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'stu_002',
    universalStudentId: 'ERP-2025-000002',
    firstName: 'Ananya',
    lastName: 'Gupta',
    dateOfBirth: '2014-07-22',
    gender: 'female',
    bloodGroup: 'B+',
    address: '45, Andheri West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400053',
    parentName: 'Suresh Gupta',
    parentPhone: '+91-98200-33333',
    parentEmail: 'suresh.gupta@yahoo.com',
    parentRelation: 'Father',
    emergencyContact: '+91-98200-44444',
    previousSchool: 'Ryan International',
    previousClass: '1st',
    createdAt: '2025-01-12T14:30:00Z',
  },
  {
    id: 'stu_003',
    universalStudentId: 'ERP-2025-000003',
    firstName: 'Vihaan',
    lastName: 'Reddy',
    dateOfBirth: '2016-01-05',
    gender: 'male',
    bloodGroup: 'A+',
    address: '78, Whitefield Road',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560066',
    parentName: 'Lakshmi Reddy',
    parentPhone: '+91-98450-55555',
    parentEmail: 'lakshmi.reddy@outlook.com',
    parentRelation: 'Mother',
    emergencyContact: '+91-98450-66666',
    previousSchool: 'Kidzee',
    previousClass: 'LKG',
    createdAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'stu_004',
    universalStudentId: 'ERP-2025-000004',
    firstName: 'Diya',
    lastName: 'Patel',
    dateOfBirth: '2015-11-18',
    gender: 'female',
    bloodGroup: 'AB+',
    address: '23, Gomti Nagar',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    pincode: '226010',
    parentName: 'Meena Patel',
    parentPhone: '+91-98300-77777',
    parentEmail: 'meena.patel@gmail.com',
    parentRelation: 'Mother',
    emergencyContact: '+91-98300-88888',
    previousSchool: 'Bright Beginnings',
    previousClass: 'UKG',
    createdAt: '2025-01-18T11:00:00Z',
  },
  {
    id: 'stu_005',
    universalStudentId: 'ERP-2025-000005',
    firstName: 'Aditya',
    lastName: 'Kumar',
    dateOfBirth: '2014-09-30',
    gender: 'male',
    bloodGroup: 'O-',
    address: '67, Salt Lake Sector 3',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700106',
    parentName: 'Amit Kumar',
    parentPhone: '+91-98600-99999',
    parentEmail: 'amit.kumar@rediff.com',
    parentRelation: 'Father',
    emergencyContact: '+91-98600-00000',
    previousSchool: 'Delhi Public School Ruby Park',
    previousClass: '2nd',
    createdAt: '2025-01-20T08:30:00Z',
  },
  {
    id: 'stu_006',
    universalStudentId: 'ERP-2025-000006',
    firstName: 'Sara',
    lastName: 'Khan',
    dateOfBirth: '2015-05-14',
    gender: 'female',
    bloodGroup: 'A-',
    address: '89, Kalyani Nagar',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411006',
    parentName: 'Fatima Khan',
    parentPhone: '+91-98500-12121',
    parentEmail: 'fatima.khan@gmail.com',
    parentRelation: 'Mother',
    emergencyContact: '+91-98500-23232',
    previousSchool: 'EuroSchool',
    previousClass: '1st',
    createdAt: '2025-01-22T15:00:00Z',
  },
  {
    id: 'stu_007',
    universalStudentId: 'ERP-2025-000007',
    firstName: 'Rohan',
    lastName: 'Iyer',
    dateOfBirth: '2016-02-28',
    gender: 'male',
    bloodGroup: 'B+',
    address: '34, Adyar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600020',
    parentName: 'Kavita Iyer',
    parentPhone: '+91-98800-34343',
    parentEmail: 'kavita.iyer@hotmail.com',
    parentRelation: 'Mother',
    emergencyContact: '+91-98800-45454',
    previousSchool: 'Apple Kids',
    previousClass: 'LKG',
    createdAt: '2025-01-25T10:30:00Z',
  },
  {
    id: 'stu_008',
    universalStudentId: 'ERP-2025-000008',
    firstName: 'Meera',
    lastName: 'Verma',
    dateOfBirth: '2014-12-10',
    gender: 'female',
    bloodGroup: 'O+',
    address: '56, Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500034',
    parentName: 'Sanjay Verma',
    parentPhone: '+91-98700-56565',
    parentEmail: 'sanjay.verma@gmail.com',
    parentRelation: 'Father',
    emergencyContact: '+91-98700-67676',
    previousSchool: 'Chirec International',
    previousClass: '3rd',
    createdAt: '2025-01-28T09:00:00Z',
  },
  {
    id: 'stu_009',
    universalStudentId: 'ERP-2025-000009',
    firstName: 'Kabir',
    lastName: 'Malhotra',
    dateOfBirth: '2015-08-20',
    gender: 'male',
    bloodGroup: 'A+',
    address: '78, Greater Kailash',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110048',
    parentName: 'Neha Malhotra',
    parentPhone: '+91-98110-78787',
    parentEmail: 'neha.malhotra@yahoo.com',
    parentRelation: 'Mother',
    emergencyContact: '+91-98110-89898',
    previousSchool: 'The Shri Ram School',
    previousClass: 'UKG',
    createdAt: '2025-02-01T11:00:00Z',
  },
  {
    id: 'stu_010',
    universalStudentId: 'ERP-2025-000010',
    firstName: 'Isha',
    lastName: 'Nair',
    dateOfBirth: '2015-04-03',
    gender: 'female',
    bloodGroup: 'B-',
    address: '90, Juhu Beach Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400049',
    parentName: 'Arun Nair',
    parentPhone: '+91-98220-90909',
    parentEmail: 'arun.nair@gmail.com',
    parentRelation: 'Father',
    emergencyContact: '+91-98220-01010',
    previousSchool: 'Bombay Scottish',
    previousClass: '1st',
    createdAt: '2025-02-05T14:00:00Z',
  },
  {
    id: 'stu_011',
    universalStudentId: 'ERP-2025-000011',
    firstName: 'Dev',
    lastName: 'Chauhan',
    dateOfBirth: '2016-06-15',
    gender: 'male',
    bloodGroup: 'AB-',
    address: '11, Koramangala',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560034',
    parentName: 'Pooja Chauhan',
    parentPhone: '+91-98460-12122',
    parentEmail: 'pooja.chauhan@outlook.com',
    parentRelation: 'Mother',
    emergencyContact: '+91-98460-23233',
    previousSchool: 'Head Start',
    previousClass: 'LKG',
    createdAt: '2025-02-08T08:00:00Z',
  },
  {
    id: 'stu_012',
    universalStudentId: 'ERP-2025-000012',
    firstName: 'Priya',
    lastName: 'Agarwal',
    dateOfBirth: '2015-01-25',
    gender: 'female',
    bloodGroup: 'O+',
    address: '22, Hazratganj',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    pincode: '226001',
    parentName: 'Vikas Agarwal',
    parentPhone: '+91-98320-34344',
    parentEmail: 'vikas.agarwal@gmail.com',
    parentRelation: 'Father',
    emergencyContact: '+91-98320-45455',
    previousSchool: 'Cathedral School',
    previousClass: '1st',
    createdAt: '2025-02-10T10:30:00Z',
  },
  {
    id: 'stu_013',
    universalStudentId: 'ERP-2025-000013',
    firstName: 'Yuvraj',
    lastName: 'Das',
    dateOfBirth: '2014-10-08',
    gender: 'male',
    bloodGroup: 'A+',
    address: '33, Park Street',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700016',
    parentName: 'Sunita Das',
    parentPhone: '+91-98630-56567',
    parentEmail: 'sunita.das@yahoo.com',
    parentRelation: 'Mother',
    emergencyContact: '+91-98630-67678',
    previousSchool: 'La Martiniere',
    previousClass: '2nd',
    createdAt: '2025-02-12T13:00:00Z',
  },
  {
    id: 'stu_014',
    universalStudentId: 'ERP-2025-000014',
    firstName: 'Anika',
    lastName: 'Joshi',
    dateOfBirth: '2015-09-12',
    gender: 'female',
    bloodGroup: 'B+',
    address: '44, Viman Nagar',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411014',
    parentName: 'Rahul Joshi',
    parentPhone: '+91-98540-78789',
    parentEmail: 'rahul.joshi@gmail.com',
    parentRelation: 'Father',
    emergencyContact: '+91-98540-89890',
    previousSchool: 'Wisdom World School',
    previousClass: 'UKG',
    createdAt: '2025-02-15T09:30:00Z',
  },
  {
    id: 'stu_015',
    universalStudentId: 'ERP-2025-000015',
    firstName: 'Arjun',
    lastName: 'Menon',
    dateOfBirth: '2016-03-18',
    gender: 'male',
    bloodGroup: 'O+',
    address: '55, Anna Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600040',
    parentName: 'Divya Menon',
    parentPhone: '+91-98850-90901',
    parentEmail: 'divya.menon@outlook.com',
    parentRelation: 'Mother',
    emergencyContact: '+91-98850-01012',
    previousSchool: 'PSBB Millennium',
    previousClass: 'LKG',
    createdAt: '2025-02-18T11:00:00Z',
  },
];

// ── Interview Tickets ─────────────────────────────────────────────────────────

export const interviewTickets: InterviewTicket[] = [
  {
    id: 'tkt_001',
    ticketNumber: 'INT-DPS-250001',
    submissionId: 'APP-2025-001',
    studentId: 'stu_001',
    schoolId: 'sch_001',
    studentName: 'Aarav Sharma',
    schoolName: 'Delhi Public School',
    interviewDate: '2025-03-15',
    interviewTime: '09:00 AM',
    venue: 'DPS Main Campus, Admin Block',
    instructions: 'Bring original documents. Dress code: School uniform. Reporting time: 8:30 AM.',
    ticketQrCode: 'INT-DPS-250001-QR',
    status: 'generated',
    createdAt: '2025-02-10T10:00:00Z',
  },
  {
    id: 'tkt_002',
    ticketNumber: 'INT-SXA-250002',
    submissionId: 'APP-2025-002',
    studentId: 'stu_002',
    schoolId: 'sch_002',
    studentName: 'Ananya Gupta',
    schoolName: "St. Xavier's Academy",
    interviewDate: '2025-03-18',
    interviewTime: '10:30 AM',
    venue: "St. Xavier's Academy, Principal's Office",
    instructions: 'Bring previous school records. Both parents required.',
    ticketQrCode: 'INT-SXA-250002-QR',
    status: 'printed',
    printedByVendor: 'ven_002',
    printedAt: '2025-02-12T14:30:00Z',
    createdAt: '2025-02-10T12:00:00Z',
  },
  {
    id: 'tkt_003',
    ticketNumber: 'INT-GWI-250003',
    submissionId: 'APP-2025-003',
    studentId: 'stu_003',
    schoolId: 'sch_003',
    studentName: 'Vihaan Reddy',
    schoolName: 'Greenwood International',
    interviewDate: '2025-03-20',
    interviewTime: '11:00 AM',
    venue: 'Greenwood International, Admission Centre',
    instructions: 'IB assessment test included. Duration: 2 hours. Bring stationery.',
    ticketQrCode: 'INT-GWI-250003-QR',
    status: 'downloaded',
    createdAt: '2025-02-11T09:00:00Z',
  },
  {
    id: 'tkt_004',
    ticketNumber: 'INT-CMS-250004',
    submissionId: 'APP-2025-004',
    studentId: 'stu_004',
    schoolId: 'sch_004',
    studentName: 'Diya Patel',
    schoolName: 'City Montessori School',
    interviewDate: '2025-03-22',
    interviewTime: '09:30 AM',
    venue: 'CMS Gomti Nagar Campus',
    instructions: 'General aptitude test followed by parent interaction.',
    ticketQrCode: 'INT-CMS-250004-QR',
    status: 'used',
    createdAt: '2025-02-12T11:00:00Z',
  },
  {
    id: 'tkt_005',
    ticketNumber: 'INT-THS-250005',
    submissionId: 'APP-2025-005',
    studentId: 'stu_005',
    schoolId: 'sch_005',
    studentName: 'Aditya Kumar',
    schoolName: 'The Heritage School',
    interviewDate: '2025-03-25',
    interviewTime: '10:00 AM',
    venue: 'Heritage School, Salt Lake',
    instructions: 'Bring transfer certificate and previous marksheet.',
    ticketQrCode: 'INT-THS-250005-QR',
    status: 'generated',
    createdAt: '2025-02-13T08:30:00Z',
  },
  {
    id: 'tkt_006',
    ticketNumber: 'INT-POD-250006',
    submissionId: 'APP-2025-006',
    studentId: 'stu_006',
    schoolId: 'sch_006',
    studentName: 'Sara Khan',
    schoolName: 'Podar International',
    interviewDate: '2025-03-28',
    interviewTime: '02:00 PM',
    venue: 'Podar International, Kalyani Nagar',
    instructions: 'STEM activity session. Child should wear comfortable clothes.',
    ticketQrCode: 'INT-POD-250006-QR',
    status: 'printed',
    printedByVendor: 'ven_005',
    printedAt: '2025-02-14T10:00:00Z',
    createdAt: '2025-02-13T15:00:00Z',
  },
  {
    id: 'tkt_007',
    ticketNumber: 'INT-DPS-250007',
    submissionId: 'APP-2025-007',
    studentId: 'stu_009',
    schoolId: 'sch_001',
    studentName: 'Kabir Malhotra',
    schoolName: 'Delhi Public School',
    interviewDate: '2025-04-01',
    interviewTime: '09:00 AM',
    venue: 'DPS Main Campus, Admin Block',
    instructions: 'Bring original documents. Dress code: School uniform.',
    ticketQrCode: 'INT-DPS-250007-QR',
    status: 'generated',
    createdAt: '2025-02-15T11:00:00Z',
  },
  {
    id: 'tkt_008',
    ticketNumber: 'INT-SXA-250008',
    submissionId: 'APP-2025-008',
    studentId: 'stu_010',
    schoolId: 'sch_002',
    studentName: 'Isha Nair',
    schoolName: "St. Xavier's Academy",
    interviewDate: '2025-04-05',
    interviewTime: '11:00 AM',
    venue: "St. Xavier's Academy",
    instructions: 'Both parents required. Bring original documents.',
    ticketQrCode: 'INT-SXA-250008-QR',
    status: 'expired',
    createdAt: '2025-02-16T14:00:00Z',
  },
  {
    id: 'tkt_009',
    ticketNumber: 'INT-GWI-250009',
    submissionId: 'APP-2025-009',
    studentId: 'stu_011',
    schoolId: 'sch_003',
    studentName: 'Dev Chauhan',
    schoolName: 'Greenwood International',
    interviewDate: '2025-04-08',
    interviewTime: '10:00 AM',
    venue: 'Greenwood International',
    instructions: 'PYP assessment. Interactive play-based evaluation.',
    ticketQrCode: 'INT-GWI-250009-QR',
    status: 'generated',
    createdAt: '2025-02-17T08:00:00Z',
  },
  {
    id: 'tkt_010',
    ticketNumber: 'INT-CMS-250010',
    submissionId: 'APP-2025-010',
    studentId: 'stu_012',
    schoolId: 'sch_004',
    studentName: 'Priya Agarwal',
    schoolName: 'City Montessori School',
    interviewDate: '2025-04-10',
    interviewTime: '09:00 AM',
    venue: 'CMS Gomti Nagar',
    instructions: 'General interaction and basic assessment.',
    ticketQrCode: 'INT-CMS-250010-QR',
    status: 'downloaded',
    createdAt: '2025-02-18T10:30:00Z',
  },
  {
    id: 'tkt_011',
    ticketNumber: 'INT-THS-250011',
    submissionId: 'APP-2025-011',
    studentId: 'stu_013',
    schoolId: 'sch_005',
    studentName: 'Yuvraj Das',
    schoolName: 'The Heritage School',
    interviewDate: '2025-04-12',
    interviewTime: '10:30 AM',
    venue: 'Heritage School, Main Campus',
    instructions: 'Academic review and extracurricular discussion.',
    ticketQrCode: 'INT-THS-250011-QR',
    status: 'printed',
    printedByVendor: 'ven_001',
    printedAt: '2025-02-19T09:00:00Z',
    createdAt: '2025-02-18T13:00:00Z',
  },
  {
    id: 'tkt_012',
    ticketNumber: 'INT-POD-250012',
    submissionId: 'APP-2025-012',
    studentId: 'stu_014',
    schoolId: 'sch_006',
    studentName: 'Anika Joshi',
    schoolName: 'Podar International',
    interviewDate: '2025-04-15',
    interviewTime: '11:30 AM',
    venue: 'Podar International Pune',
    instructions: 'Aptitude test and parent interview.',
    ticketQrCode: 'INT-POD-250012-QR',
    status: 'generated',
    createdAt: '2025-02-19T09:30:00Z',
  },
  {
    id: 'tkt_013',
    ticketNumber: 'INT-SVM-250013',
    submissionId: 'APP-2025-013',
    studentId: 'stu_007',
    schoolId: 'sch_007',
    studentName: 'Rohan Iyer',
    schoolName: 'Saraswati Vidya Mandir',
    interviewDate: '2025-04-18',
    interviewTime: '09:30 AM',
    venue: 'SVM Adyar Campus',
    instructions: 'Basic evaluation in Tamil and English.',
    ticketQrCode: 'INT-SVM-250013-QR',
    status: 'generated',
    createdAt: '2025-02-20T10:30:00Z',
  },
  {
    id: 'tkt_014',
    ticketNumber: 'INT-GIS-250014',
    submissionId: 'APP-2025-014',
    studentId: 'stu_008',
    schoolId: 'sch_008',
    studentName: 'Meera Verma',
    schoolName: 'Global International School',
    interviewDate: '2025-04-20',
    interviewTime: '10:00 AM',
    venue: 'GIS Banjara Hills',
    instructions: 'IB entrance assessment. 3 hour session.',
    ticketQrCode: 'INT-GIS-250014-QR',
    status: 'downloaded',
    createdAt: '2025-02-20T09:00:00Z',
  },
  {
    id: 'tkt_015',
    ticketNumber: 'INT-DPS-250015',
    submissionId: 'APP-2025-015',
    studentId: 'stu_001',
    schoolId: 'sch_001',
    studentName: 'Aarav Sharma',
    schoolName: 'Delhi Public School',
    interviewDate: '2025-04-22',
    interviewTime: '02:00 PM',
    venue: 'DPS Main Campus',
    instructions: 'Follow-up interaction for Class 1 admission.',
    ticketQrCode: 'INT-DPS-250015-QR',
    status: 'generated',
    createdAt: '2025-02-21T11:00:00Z',
  },
];

// ── Applications ──────────────────────────────────────────────────────────────

export const applications: Application[] = [
  {
    id: 'app_001',
    submissionId: 'APP-2025-001',
    studentId: 'stu_001',
    schoolId: 'sch_001',
    schoolName: 'Delhi Public School',
    studentName: 'Aarav Sharma',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 500,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_001',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[0]],
    documentsSubmitted: ['doc_001', 'doc_002', 'doc_003'],
    createdAt: '2025-02-10T10:00:00Z',
    updatedAt: '2025-02-10T14:00:00Z',
  },
  {
    id: 'app_002',
    submissionId: 'APP-2025-002',
    studentId: 'stu_002',
    schoolId: 'sch_002',
    schoolName: "St. Xavier's Academy",
    studentName: 'Ananya Gupta',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 650,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_002',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[1]],
    documentsSubmitted: ['doc_004', 'doc_005', 'doc_006'],
    createdAt: '2025-02-12T14:30:00Z',
    updatedAt: '2025-02-12T16:00:00Z',
  },
  {
    id: 'app_003',
    submissionId: 'APP-2025-003',
    studentId: 'stu_003',
    schoolId: 'sch_003',
    schoolName: 'Greenwood International',
    studentName: 'Vihaan Reddy',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 1200,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_003',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[2]],
    documentsSubmitted: ['doc_007', 'doc_008'],
    createdAt: '2025-02-11T09:00:00Z',
    updatedAt: '2025-02-11T12:00:00Z',
  },
  {
    id: 'app_004',
    submissionId: 'APP-2025-004',
    studentId: 'stu_004',
    schoolId: 'sch_004',
    schoolName: 'City Montessori School',
    studentName: 'Diya Patel',
    formType: 'admission',
    status: 'accepted',
    totalAmount: 350,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_001',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[3]],
    documentsSubmitted: ['doc_009', 'doc_010', 'doc_011'],
    notes: 'Application accepted! Welcome to CMS.',
    createdAt: '2025-02-12T11:00:00Z',
    updatedAt: '2025-02-25T10:00:00Z',
  },
  {
    id: 'app_005',
    submissionId: 'APP-2025-005',
    studentId: 'stu_005',
    schoolId: 'sch_005',
    schoolName: 'The Heritage School',
    studentName: 'Aditya Kumar',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 300,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_001',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[4]],
    documentsSubmitted: ['doc_012', 'doc_013'],
    createdAt: '2025-02-13T08:30:00Z',
    updatedAt: '2025-02-13T11:00:00Z',
  },
  {
    id: 'app_006',
    submissionId: 'APP-2025-006',
    studentId: 'stu_006',
    schoolId: 'sch_006',
    schoolName: 'Podar International',
    studentName: 'Sara Khan',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 750,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_005',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[5]],
    documentsSubmitted: ['doc_014', 'doc_015'],
    createdAt: '2025-02-13T15:00:00Z',
    updatedAt: '2025-02-13T17:00:00Z',
  },
  {
    id: 'app_007',
    submissionId: 'APP-2025-007',
    studentId: 'stu_009',
    schoolId: 'sch_001',
    schoolName: 'Delhi Public School',
    studentName: 'Kabir Malhotra',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 500,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_001',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[6]],
    documentsSubmitted: ['doc_016', 'doc_017'],
    createdAt: '2025-02-15T11:00:00Z',
    updatedAt: '2025-02-15T14:00:00Z',
  },
  {
    id: 'app_008',
    submissionId: 'APP-2025-008',
    studentId: 'stu_010',
    schoolId: 'sch_002',
    schoolName: "St. Xavier's Academy",
    studentName: 'Isha Nair',
    formType: 'admission',
    status: 'rejected',
    totalAmount: 650,
    paymentStatus: 'refunded',
    assignedVendorId: 'ven_002',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[7]],
    documentsSubmitted: ['doc_018', 'doc_019'],
    notes: 'Seat not available. Refund processed.',
    createdAt: '2025-02-16T14:00:00Z',
    updatedAt: '2025-02-28T09:00:00Z',
  },
  {
    id: 'app_009',
    submissionId: 'APP-2025-009',
    studentId: 'stu_011',
    schoolId: 'sch_003',
    schoolName: 'Greenwood International',
    studentName: 'Dev Chauhan',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 1200,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_003',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[8]],
    documentsSubmitted: ['doc_020', 'doc_021'],
    createdAt: '2025-02-17T08:00:00Z',
    updatedAt: '2025-02-17T11:00:00Z',
  },
  {
    id: 'app_010',
    submissionId: 'APP-2025-010',
    studentId: 'stu_012',
    schoolId: 'sch_004',
    schoolName: 'City Montessori School',
    studentName: 'Priya Agarwal',
    formType: 'admission',
    status: 'under_review',
    totalAmount: 350,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_001',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[9]],
    documentsSubmitted: ['doc_022', 'doc_023'],
    createdAt: '2025-02-18T10:30:00Z',
    updatedAt: '2025-02-18T14:00:00Z',
  },
  {
    id: 'app_011',
    submissionId: 'APP-2025-011',
    studentId: 'stu_013',
    schoolId: 'sch_005',
    schoolName: 'The Heritage School',
    studentName: 'Yuvraj Das',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 300,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_004',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[10]],
    documentsSubmitted: ['doc_024', 'doc_025'],
    createdAt: '2025-02-18T13:00:00Z',
    updatedAt: '2025-02-18T15:00:00Z',
  },
  {
    id: 'app_012',
    submissionId: 'APP-2025-012',
    studentId: 'stu_014',
    schoolId: 'sch_006',
    schoolName: 'Podar International',
    studentName: 'Anika Joshi',
    formType: 'admission',
    status: 'pending_payment',
    totalAmount: 750,
    paymentStatus: 'pending',
    vendorPaymentConfirmed: false,
    tickets: [interviewTickets[11]],
    documentsSubmitted: [],
    createdAt: '2025-02-19T09:30:00Z',
    updatedAt: '2025-02-19T09:30:00Z',
  },
  {
    id: 'app_013',
    submissionId: 'APP-2025-013',
    studentId: 'stu_007',
    schoolId: 'sch_007',
    schoolName: 'Saraswati Vidya Mandir',
    studentName: 'Rohan Iyer',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 200,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_003',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[12]],
    documentsSubmitted: ['doc_026'],
    createdAt: '2025-02-20T10:30:00Z',
    updatedAt: '2025-02-20T13:00:00Z',
  },
  {
    id: 'app_014',
    submissionId: 'APP-2025-014',
    studentId: 'stu_008',
    schoolId: 'sch_008',
    schoolName: 'Global International School',
    studentName: 'Meera Verma',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 1500,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_005',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[13]],
    documentsSubmitted: ['doc_027', 'doc_028', 'doc_029'],
    createdAt: '2025-02-20T09:00:00Z',
    updatedAt: '2025-02-20T12:00:00Z',
  },
  {
    id: 'app_015',
    submissionId: 'APP-2025-015',
    studentId: 'stu_001',
    schoolId: 'sch_001',
    schoolName: 'Delhi Public School',
    studentName: 'Aarav Sharma',
    formType: 'enquiry',
    status: 'submitted',
    totalAmount: 100,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_001',
    vendorPaymentConfirmed: true,
    tickets: [interviewTickets[14]],
    documentsSubmitted: [],
    createdAt: '2025-02-21T11:00:00Z',
    updatedAt: '2025-02-21T11:00:00Z',
  },
  {
    id: 'app_016',
    submissionId: 'APP-2025-016',
    studentId: 'stu_003',
    schoolId: 'sch_001',
    schoolName: 'Delhi Public School',
    studentName: 'Vihaan Reddy',
    formType: 'admission',
    status: 'waitlisted',
    totalAmount: 500,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_003',
    vendorPaymentConfirmed: true,
    tickets: [],
    documentsSubmitted: ['doc_030'],
    notes: 'Waitlist #23. Will be notified if seat opens.',
    createdAt: '2025-02-22T10:00:00Z',
    updatedAt: '2025-02-26T09:00:00Z',
  },
  {
    id: 'app_017',
    submissionId: 'APP-2025-017',
    studentId: 'stu_005',
    schoolId: 'sch_002',
    schoolName: "St. Xavier's Academy",
    studentName: 'Aditya Kumar',
    formType: 'admission',
    status: 'submitted',
    totalAmount: 650,
    paymentStatus: 'pending',
    vendorPaymentConfirmed: false,
    tickets: [],
    documentsSubmitted: [],
    createdAt: '2025-02-23T08:00:00Z',
    updatedAt: '2025-02-23T08:00:00Z',
  },
  {
    id: 'app_018',
    submissionId: 'APP-2025-018',
    studentId: 'stu_002',
    schoolId: 'sch_003',
    schoolName: 'Greenwood International',
    studentName: 'Ananya Gupta',
    formType: 'scholarship',
    status: 'under_review',
    totalAmount: 0,
    paymentStatus: 'completed',
    vendorPaymentConfirmed: false,
    tickets: [],
    documentsSubmitted: ['doc_031', 'doc_032'],
    notes: 'Scholarship application under academic review.',
    createdAt: '2025-02-24T14:00:00Z',
    updatedAt: '2025-02-27T11:00:00Z',
  },
  {
    id: 'app_019',
    submissionId: 'APP-2025-019',
    studentId: 'stu_006',
    schoolId: 'sch_004',
    schoolName: 'City Montessori School',
    studentName: 'Sara Khan',
    formType: 'transfer',
    status: 'submitted',
    totalAmount: 500,
    paymentStatus: 'pending',
    vendorPaymentConfirmed: false,
    tickets: [],
    documentsSubmitted: ['doc_033'],
    createdAt: '2025-02-25T09:30:00Z',
    updatedAt: '2025-02-25T09:30:00Z',
  },
  {
    id: 'app_020',
    submissionId: 'APP-2025-020',
    studentId: 'stu_015',
    schoolId: 'sch_007',
    schoolName: 'Saraswati Vidya Mandir',
    studentName: 'Arjun Menon',
    formType: 'admission',
    status: 'pending_payment',
    totalAmount: 200,
    paymentStatus: 'pending',
    vendorPaymentConfirmed: false,
    tickets: [],
    documentsSubmitted: [],
    createdAt: '2025-02-26T11:00:00Z',
    updatedAt: '2025-02-26T11:00:00Z',
  },
  {
    id: 'app_021',
    submissionId: 'APP-2025-021',
    studentId: 'stu_004',
    schoolId: 'sch_006',
    schoolName: 'Podar International',
    studentName: 'Diya Patel',
    formType: 'admission',
    status: 'interview_scheduled',
    totalAmount: 750,
    paymentStatus: 'completed',
    assignedVendorId: 'ven_005',
    vendorPaymentConfirmed: true,
    tickets: [],
    documentsSubmitted: ['doc_034', 'doc_035'],
    createdAt: '2025-02-27T10:00:00Z',
    updatedAt: '2025-02-27T14:00:00Z',
  },
  {
    id: 'app_022',
    submissionId: 'APP-2025-022',
    studentId: 'stu_009',
    schoolId: 'sch_008',
    schoolName: 'Global International School',
    studentName: 'Kabir Malhotra',
    formType: 'admission',
    status: 'submitted',
    totalAmount: 1500,
    paymentStatus: 'pending',
    vendorPaymentConfirmed: false,
    tickets: [],
    documentsSubmitted: [],
    createdAt: '2025-02-28T09:00:00Z',
    updatedAt: '2025-02-28T09:00:00Z',
  },
];

// ── Vault Documents ───────────────────────────────────────────────────────────

export const vaultDocuments: VaultDocument[] = [
  {
    id: 'doc_001',
    studentId: 'stu_001',
    documentType: 'birth_certificate',
    fileUrl: '/docs/birth_certificate_aarav.pdf',
    fileName: 'Birth_Certificate_Aarav.pdf',
    uploadDate: '2025-01-15T10:00:00Z',
    verificationStatus: 'blockchain_anchored',
    aiConfidenceScore: 0.98,
    blockchainHash: '0x7f8a9b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef12',
    blockchainAnchoredAt: '2025-01-16T08:00:00Z',
    fileSize: 1024000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_002',
    studentId: 'stu_001',
    documentType: 'marksheet',
    fileUrl: '/docs/marksheet_aarav.pdf',
    fileName: 'Marksheet_UKG_Aarav.pdf',
    uploadDate: '2025-01-15T10:30:00Z',
    verificationStatus: 'blockchain_anchored',
    aiConfidenceScore: 0.95,
    blockchainHash: '0x8a9b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef1234',
    blockchainAnchoredAt: '2025-01-16T08:30:00Z',
    fileSize: 2048000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_003',
    studentId: 'stu_001',
    documentType: 'aadhar_card',
    fileUrl: '/docs/aadhar_aarav.pdf',
    fileName: 'Aadhar_Aarav.pdf',
    uploadDate: '2025-01-15T11:00:00Z',
    verificationStatus: 'verified',
    aiConfidenceScore: 0.97,
    fileSize: 512000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_004',
    studentId: 'stu_002',
    documentType: 'birth_certificate',
    fileUrl: '/docs/birth_certificate_ananya.pdf',
    fileName: 'Birth_Certificate_Ananya.pdf',
    uploadDate: '2025-01-18T09:00:00Z',
    verificationStatus: 'blockchain_anchored',
    aiConfidenceScore: 0.99,
    blockchainHash: '0x9b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456',
    blockchainAnchoredAt: '2025-01-19T07:00:00Z',
    fileSize: 1024000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_005',
    studentId: 'stu_002',
    documentType: 'marksheet',
    fileUrl: '/docs/marksheet_ananya.pdf',
    fileName: 'Marksheet_Class1_Ananya.pdf',
    uploadDate: '2025-01-18T09:30:00Z',
    verificationStatus: 'verified',
    aiConfidenceScore: 0.94,
    fileSize: 1536000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_006',
    studentId: 'stu_002',
    documentType: 'transfer_certificate',
    fileUrl: '/docs/tc_ananya.pdf',
    fileName: 'Transfer_Certificate_Ananya.pdf',
    uploadDate: '2025-01-18T10:00:00Z',
    verificationStatus: 'pending',
    fileSize: 768000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_007',
    studentId: 'stu_003',
    documentType: 'birth_certificate',
    fileUrl: '/docs/birth_certificate_vihaan.pdf',
    fileName: 'Birth_Certificate_Vihaan.pdf',
    uploadDate: '2025-01-20T08:00:00Z',
    verificationStatus: 'blockchain_anchored',
    aiConfidenceScore: 0.96,
    blockchainHash: '0x2c3d4e5f6789012345678901234567890abcdef1234567890abcdef12345678',
    blockchainAnchoredAt: '2025-01-21T06:00:00Z',
    fileSize: 896000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_008',
    studentId: 'stu_003',
    documentType: 'medical_record',
    fileUrl: '/docs/medical_vihaan.pdf',
    fileName: 'Medical_Record_Vihaan.pdf',
    uploadDate: '2025-01-20T08:30:00Z',
    verificationStatus: 'verified',
    aiConfidenceScore: 0.91,
    fileSize: 640000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_009',
    studentId: 'stu_004',
    documentType: 'birth_certificate',
    fileUrl: '/docs/birth_certificate_diya.pdf',
    fileName: 'Birth_Certificate_Diya.pdf',
    uploadDate: '2025-01-22T11:00:00Z',
    verificationStatus: 'blockchain_anchored',
    aiConfidenceScore: 0.98,
    blockchainHash: '0x3d4e5f6789012345678901234567890abcdef1234567890abcdef1234567890',
    blockchainAnchoredAt: '2025-01-23T09:00:00Z',
    fileSize: 1024000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_010',
    studentId: 'stu_004',
    documentType: 'marksheet',
    fileUrl: '/docs/marksheet_diya.pdf',
    fileName: 'Marksheet_UKG_Diya.pdf',
    uploadDate: '2025-01-22T11:30:00Z',
    verificationStatus: 'verified',
    aiConfidenceScore: 0.93,
    fileSize: 1280000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_011',
    studentId: 'stu_004',
    documentType: 'address_proof',
    fileUrl: '/docs/address_diya.pdf',
    fileName: 'Address_Proof_Diya.pdf',
    uploadDate: '2025-01-22T12:00:00Z',
    verificationStatus: 'pending',
    fileSize: 512000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_012',
    studentId: 'stu_005',
    documentType: 'birth_certificate',
    fileUrl: '/docs/birth_certificate_aditya.pdf',
    fileName: 'Birth_Certificate_Aditya.pdf',
    uploadDate: '2025-01-25T10:00:00Z',
    verificationStatus: 'blockchain_anchored',
    aiConfidenceScore: 0.97,
    blockchainHash: '0x4e5f6789012345678901234567890abcdef1234567890abcdef123456789012',
    blockchainAnchoredAt: '2025-01-26T08:00:00Z',
    fileSize: 1024000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_013',
    studentId: 'stu_005',
    documentType: 'marksheet',
    fileUrl: '/docs/marksheet_aditya.pdf',
    fileName: 'Marksheet_Class2_Aditya.pdf',
    uploadDate: '2025-01-25T10:30:00Z',
    verificationStatus: 'verified',
    aiConfidenceScore: 0.95,
    fileSize: 1792000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_014',
    studentId: 'stu_006',
    documentType: 'birth_certificate',
    fileUrl: '/docs/birth_certificate_sara.pdf',
    fileName: 'Birth_Certificate_Sara.pdf',
    uploadDate: '2025-01-28T14:00:00Z',
    verificationStatus: 'verified',
    aiConfidenceScore: 0.92,
    fileSize: 768000,
    mimeType: 'application/pdf',
  },
  {
    id: 'doc_015',
    studentId: 'stu_006',
    documentType: 'marksheet',
    fileUrl: '/docs/marksheet_sara.pdf',
    fileName: 'Marksheet_Class1_Sara.pdf',
    uploadDate: '2025-01-28T14:30:00Z',
    verificationStatus: 'pending',
    fileSize: 1024000,
    mimeType: 'application/pdf',
  },
];

// ── Form Catalog ──────────────────────────────────────────────────────────────

export const formCatalog: FormCatalogItem[] = [
  {
    id: 'form_001',
    schoolId: 'sch_001',
    schoolName: 'Delhi Public School',
    formType: 'admission',
    title: 'DPS Admission Form 2025-26',
    description: 'Admission form for Nursery to Class 8. Includes application fee and processing charges.',
    basePrice: 500,
    demandAdjustedPrice: 500,
    bulkDiscountThreshold: 3,
    bulkDiscountPercent: 10,
    requiredDocuments: ['birth_certificate', 'marksheet', 'aadhar_card'],
    eligibilityCriteria: ['Age 3+ for Nursery', 'Resident of Delhi NCR'],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-03-31',
    maxQuantityPerStudent: 2,
    isActive: true,
  },
  {
    id: 'form_002',
    schoolId: 'sch_002',
    schoolName: "St. Xavier's Academy",
    formType: 'admission',
    title: "St. Xavier's Admission Form 2025-26",
    description: 'ICSE admission form for all classes. Includes entrance test fee.',
    basePrice: 650,
    demandAdjustedPrice: 650,
    bulkDiscountThreshold: 2,
    bulkDiscountPercent: 5,
    requiredDocuments: ['birth_certificate', 'marksheet', 'transfer_certificate'],
    eligibilityCriteria: ['Age appropriate for class', 'Valid school leaving certificate'],
    saleStartDate: '2025-01-15',
    saleEndDate: '2025-04-15',
    maxQuantityPerStudent: 1,
    isActive: true,
  },
  {
    id: 'form_003',
    schoolId: 'sch_003',
    schoolName: 'Greenwood International',
    formType: 'admission',
    title: 'Greenwood IB Admission 2025-26',
    description: 'IB PYP/MYP/DP admission. Includes assessment fee.',
    basePrice: 1200,
    demandAdjustedPrice: 1200,
    bulkDiscountThreshold: 2,
    bulkDiscountPercent: 15,
    requiredDocuments: ['birth_certificate', 'marksheet', 'medical_record', 'passport_photo'],
    eligibilityCriteria: ['English proficiency', 'Previous academic record'],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-03-15',
    maxQuantityPerStudent: 1,
    isActive: true,
  },
  {
    id: 'form_004',
    schoolId: 'sch_004',
    schoolName: 'City Montessori School',
    formType: 'admission',
    title: 'CMS Admission Form 2025-26',
    description: 'Admission form for all CMS campuses in Lucknow.',
    basePrice: 350,
    demandAdjustedPrice: 350,
    bulkDiscountThreshold: 5,
    bulkDiscountPercent: 20,
    requiredDocuments: ['birth_certificate', 'marksheet'],
    eligibilityCriteria: ['Resident of Lucknow', 'Age as per CBSE norms'],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-04-30',
    maxQuantityPerStudent: 3,
    isActive: true,
  },
  {
    id: 'form_005',
    schoolId: 'sch_005',
    schoolName: 'The Heritage School',
    formType: 'admission',
    title: 'Heritage School Admission 2025-26',
    description: 'State board admission form. Affordable quality education.',
    basePrice: 300,
    demandAdjustedPrice: 300,
    bulkDiscountThreshold: 3,
    bulkDiscountPercent: 10,
    requiredDocuments: ['birth_certificate', 'marksheet', 'address_proof'],
    eligibilityCriteria: ['Resident of Kolkata', 'Income certificate for fee waiver'],
    saleStartDate: '2025-01-15',
    saleEndDate: '2025-05-31',
    maxQuantityPerStudent: 2,
    isActive: true,
  },
  {
    id: 'form_006',
    schoolId: 'sch_006',
    schoolName: 'Podar International',
    formType: 'admission',
    title: 'Podar Admission Form 2025-26',
    description: 'CBSE+IB dual board admission. STEM focused.',
    basePrice: 750,
    demandAdjustedPrice: 750,
    bulkDiscountThreshold: 2,
    bulkDiscountPercent: 10,
    requiredDocuments: ['birth_certificate', 'marksheet', 'aadhar_card'],
    eligibilityCriteria: ['Age as per board norms', 'STEM aptitude preferred'],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-04-30',
    maxQuantityPerStudent: 2,
    isActive: true,
  },
  {
    id: 'form_007',
    schoolId: 'sch_001',
    schoolName: 'Delhi Public School',
    formType: 'enquiry',
    title: 'DPS Enquiry Form',
    description: 'General enquiry form for admissions, facilities, and programs.',
    basePrice: 100,
    demandAdjustedPrice: 100,
    bulkDiscountThreshold: 5,
    bulkDiscountPercent: 0,
    requiredDocuments: [],
    eligibilityCriteria: [],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-12-31',
    maxQuantityPerStudent: 5,
    isActive: true,
  },
  {
    id: 'form_008',
    schoolId: 'sch_002',
    schoolName: "St. Xavier's Academy",
    formType: 'enquiry',
    title: "St. Xavier's Enquiry Form",
    description: 'Enquiry for admissions, fees, and school programs.',
    basePrice: 100,
    demandAdjustedPrice: 100,
    bulkDiscountThreshold: 5,
    bulkDiscountPercent: 0,
    requiredDocuments: [],
    eligibilityCriteria: [],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-12-31',
    maxQuantityPerStudent: 5,
    isActive: true,
  },
  {
    id: 'form_009',
    schoolId: 'sch_003',
    schoolName: 'Greenwood International',
    formType: 'scholarship',
    title: 'Greenwood Merit Scholarship',
    description: 'Merit-based scholarship for academically excellent students.',
    basePrice: 0,
    demandAdjustedPrice: 0,
    bulkDiscountThreshold: 1,
    bulkDiscountPercent: 0,
    requiredDocuments: ['marksheet', 'income_certificate'],
    eligibilityCriteria: ['90%+ in previous exams', 'Family income < 5 LPA'],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-02-28',
    maxQuantityPerStudent: 1,
    isActive: true,
  },
  {
    id: 'form_010',
    schoolId: 'sch_004',
    schoolName: 'City Montessori School',
    formType: 'transfer',
    title: 'CMS Transfer Admission',
    description: 'Transfer admission for students from other schools.',
    basePrice: 500,
    demandAdjustedPrice: 500,
    bulkDiscountThreshold: 1,
    bulkDiscountPercent: 0,
    requiredDocuments: ['birth_certificate', 'marksheet', 'transfer_certificate'],
    eligibilityCriteria: ['Valid TC from previous school', 'Good conduct certificate'],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-06-30',
    maxQuantityPerStudent: 1,
    isActive: true,
  },
  {
    id: 'form_011',
    schoolId: 'sch_008',
    schoolName: 'Global International School',
    formType: 'admission',
    title: 'GIS Admission 2025-26',
    description: 'Premium IB admission with comprehensive assessment.',
    basePrice: 1500,
    demandAdjustedPrice: 1500,
    bulkDiscountThreshold: 1,
    bulkDiscountPercent: 0,
    requiredDocuments: ['birth_certificate', 'marksheet', 'medical_record', 'passport_photo', 'address_proof'],
    eligibilityCriteria: ['English proficiency test', 'Family interview'],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-03-01',
    maxQuantityPerStudent: 1,
    isActive: true,
  },
  {
    id: 'form_012',
    schoolId: 'sch_007',
    schoolName: 'Saraswati Vidya Mandir',
    formType: 'admission',
    title: 'SVM Admission Form 2025-26',
    description: 'State board admission. Tamil and English medium available.',
    basePrice: 200,
    demandAdjustedPrice: 200,
    bulkDiscountThreshold: 3,
    bulkDiscountPercent: 15,
    requiredDocuments: ['birth_certificate', 'marksheet'],
    eligibilityCriteria: ['Resident of Chennai', 'Age as per state norms'],
    saleStartDate: '2025-01-01',
    saleEndDate: '2025-05-31',
    maxQuantityPerStudent: 2,
    isActive: true,
  },
];

// ── Transactions ──────────────────────────────────────────────────────────────

export const transactions: Transaction[] = [
  { id: 'txn_001', transactionId: 'TXN-2025-000001', type: 'form_sale', applicationId: 'app_001', schoolId: 'sch_001', vendorId: 'ven_001', parentId: 'stu_001', amount: 500, platformFee: 50, vendorCommission: 25, schoolRevenue: 425, tokenDeducted: 5, paymentMethod: 'cash', status: 'completed', description: 'DPS Admission Form - Aarav Sharma', createdAt: '2025-02-10T14:00:00Z' },
  { id: 'txn_002', transactionId: 'TXN-2025-000002', type: 'form_sale', applicationId: 'app_002', schoolId: 'sch_002', vendorId: 'ven_002', parentId: 'stu_002', amount: 650, platformFee: 65, vendorCommission: 32, schoolRevenue: 553, tokenDeducted: 6, paymentMethod: 'cash', status: 'completed', description: "St. Xavier's Admission - Ananya Gupta", createdAt: '2025-02-12T16:00:00Z' },
  { id: 'txn_003', transactionId: 'TXN-2025-000003', type: 'form_sale', applicationId: 'app_003', schoolId: 'sch_003', vendorId: 'ven_003', parentId: 'stu_003', amount: 1200, platformFee: 120, vendorCommission: 60, schoolRevenue: 1020, tokenDeducted: 12, paymentMethod: 'cash', status: 'completed', description: 'Greenwood Admission - Vihaan Reddy', createdAt: '2025-02-11T12:00:00Z' },
  { id: 'txn_004', transactionId: 'TXN-2025-000004', type: 'form_sale', applicationId: 'app_004', schoolId: 'sch_004', vendorId: 'ven_001', parentId: 'stu_004', amount: 350, platformFee: 35, vendorCommission: 17, schoolRevenue: 298, tokenDeducted: 3, paymentMethod: 'cash', status: 'completed', description: 'CMS Admission - Diya Patel', createdAt: '2025-02-12T14:00:00Z' },
  { id: 'txn_005', transactionId: 'TXN-2025-000005', type: 'form_sale', applicationId: 'app_005', schoolId: 'sch_005', vendorId: 'ven_001', parentId: 'stu_005', amount: 300, platformFee: 30, vendorCommission: 15, schoolRevenue: 255, tokenDeducted: 3, paymentMethod: 'cash', status: 'completed', description: 'Heritage Admission - Aditya Kumar', createdAt: '2025-02-13T11:00:00Z' },
  { id: 'txn_006', transactionId: 'TXN-2025-000006', type: 'form_sale', applicationId: 'app_006', schoolId: 'sch_006', vendorId: 'ven_005', parentId: 'stu_006', amount: 750, platformFee: 75, vendorCommission: 37, schoolRevenue: 638, tokenDeducted: 7, paymentMethod: 'cash', status: 'completed', description: 'Podar Admission - Sara Khan', createdAt: '2025-02-13T17:00:00Z' },
  { id: 'txn_007', transactionId: 'TXN-2025-000007', type: 'form_sale', applicationId: 'app_007', schoolId: 'sch_001', vendorId: 'ven_001', parentId: 'stu_009', amount: 500, platformFee: 50, vendorCommission: 25, schoolRevenue: 425, tokenDeducted: 5, paymentMethod: 'cash', status: 'completed', description: 'DPS Admission - Kabir Malhotra', createdAt: '2025-02-15T14:00:00Z' },
  { id: 'txn_008', transactionId: 'TXN-2025-000008', type: 'refund', applicationId: 'app_008', schoolId: 'sch_002', vendorId: 'ven_002', parentId: 'stu_010', amount: -650, platformFee: -65, vendorCommission: -32, schoolRevenue: -553, paymentMethod: 'cash', status: 'completed', description: "Refund - St. Xavier's Rejection - Isha Nair", createdAt: '2025-02-28T09:00:00Z' },
  { id: 'txn_009', transactionId: 'TXN-2025-000009', type: 'form_sale', applicationId: 'app_009', schoolId: 'sch_003', vendorId: 'ven_003', parentId: 'stu_011', amount: 1200, platformFee: 120, vendorCommission: 60, schoolRevenue: 1020, tokenDeducted: 12, paymentMethod: 'cash', status: 'completed', description: 'Greenwood Admission - Dev Chauhan', createdAt: '2025-02-17T11:00:00Z' },
  { id: 'txn_010', transactionId: 'TXN-2025-000010', type: 'form_sale', applicationId: 'app_010', schoolId: 'sch_004', vendorId: 'ven_001', parentId: 'stu_012', amount: 350, platformFee: 35, vendorCommission: 17, schoolRevenue: 298, tokenDeducted: 3, paymentMethod: 'cash', status: 'completed', description: 'CMS Admission - Priya Agarwal', createdAt: '2025-02-18T14:00:00Z' },
  { id: 'txn_011', transactionId: 'TXN-2025-000011', type: 'form_sale', applicationId: 'app_011', schoolId: 'sch_005', vendorId: 'ven_004', parentId: 'stu_013', amount: 300, platformFee: 30, vendorCommission: 15, schoolRevenue: 255, tokenDeducted: 3, paymentMethod: 'cash', status: 'completed', description: 'Heritage Admission - Yuvraj Das', createdAt: '2025-02-18T15:00:00Z' },
  { id: 'txn_012', transactionId: 'TXN-2025-000012', type: 'form_sale', applicationId: 'app_013', schoolId: 'sch_007', vendorId: 'ven_003', parentId: 'stu_007', amount: 200, platformFee: 20, vendorCommission: 10, schoolRevenue: 170, tokenDeducted: 2, paymentMethod: 'cash', status: 'completed', description: 'SVM Admission - Rohan Iyer', createdAt: '2025-02-20T13:00:00Z' },
  { id: 'txn_013', transactionId: 'TXN-2025-000013', type: 'form_sale', applicationId: 'app_014', schoolId: 'sch_008', vendorId: 'ven_005', parentId: 'stu_008', amount: 1500, platformFee: 150, vendorCommission: 75, schoolRevenue: 1275, tokenDeducted: 15, paymentMethod: 'cash', status: 'completed', description: 'GIS Admission - Meera Verma', createdAt: '2025-02-20T12:00:00Z' },
  { id: 'txn_014', transactionId: 'TXN-2025-000014', type: 'form_sale', applicationId: 'app_015', schoolId: 'sch_001', vendorId: 'ven_001', parentId: 'stu_001', amount: 100, platformFee: 10, vendorCommission: 5, schoolRevenue: 85, tokenDeducted: 1, paymentMethod: 'cash', status: 'completed', description: 'DPS Enquiry - Aarav Sharma', createdAt: '2025-02-21T14:00:00Z' },
  { id: 'txn_015', transactionId: 'TXN-2025-000015', type: 'form_sale', applicationId: 'app_016', schoolId: 'sch_001', vendorId: 'ven_003', parentId: 'stu_003', amount: 500, platformFee: 50, vendorCommission: 25, schoolRevenue: 425, tokenDeducted: 5, paymentMethod: 'cash', status: 'completed', description: 'DPS Waitlist - Vihaan Reddy', createdAt: '2025-02-22T12:00:00Z' },
  { id: 'txn_016', transactionId: 'TXN-2025-000016', type: 'vendor_commission', vendorId: 'ven_001', amount: 250, platformFee: 0, vendorCommission: 250, schoolRevenue: 0, paymentMethod: 'token', status: 'completed', description: 'Weekly commission payout - VEN001', createdAt: '2025-02-24T10:00:00Z' },
  { id: 'txn_017', transactionId: 'TXN-2025-000017', type: 'vendor_commission', vendorId: 'ven_003', amount: 320, platformFee: 0, vendorCommission: 320, schoolRevenue: 0, paymentMethod: 'token', status: 'completed', description: 'Weekly commission payout - VEN003', createdAt: '2025-02-24T10:00:00Z' },
  { id: 'txn_018', transactionId: 'TXN-2025-000018', type: 'platform_fee', amount: 875, platformFee: 875, vendorCommission: 0, schoolRevenue: 0, paymentMethod: 'online', status: 'completed', description: 'Platform fees collection - Week 8', createdAt: '2025-02-24T12:00:00Z' },
  { id: 'txn_019', transactionId: 'TXN-2025-000019', type: 'token_topup', vendorId: 'ven_002', amount: 500, platformFee: 0, vendorCommission: 0, schoolRevenue: 0, paymentMethod: 'online', status: 'completed', description: 'Token top-up - VEN002', createdAt: '2025-02-25T09:00:00Z' },
  { id: 'txn_020', transactionId: 'TXN-2025-000020', type: 'form_sale', applicationId: 'app_021', schoolId: 'sch_006', vendorId: 'ven_005', parentId: 'stu_004', amount: 750, platformFee: 75, vendorCommission: 37, schoolRevenue: 638, tokenDeducted: 7, paymentMethod: 'cash', status: 'completed', description: 'Podar Admission - Diya Patel', createdAt: '2025-02-27T14:00:00Z' },
  { id: 'txn_021', transactionId: 'TXN-2025-000021', type: 'form_sale', applicationId: 'app_018', schoolId: 'sch_003', parentId: 'stu_002', amount: 0, platformFee: 0, vendorCommission: 0, schoolRevenue: 0, paymentMethod: 'cash', status: 'completed', description: 'Greenwood Scholarship - Ananya Gupta', createdAt: '2025-02-24T14:00:00Z' },
  { id: 'txn_022', transactionId: 'TXN-2025-000022', type: 'form_sale', applicationId: 'app_019', schoolId: 'sch_004', parentId: 'stu_006', amount: 500, platformFee: 50, vendorCommission: 25, schoolRevenue: 425, paymentMethod: 'cash', status: 'pending', description: 'CMS Transfer - Sara Khan', createdAt: '2025-02-25T09:30:00Z' },
];

// ── User Accounts ─────────────────────────────────────────────────────────────

export const userAccounts: UserAccount[] = [
  {
    id: 'usr_001',
    userId: 'USR001',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@gmail.com',
    phone: '+91-98100-11111',
    role: 'parent',
    zone: 'parent',
    isActive: true,
    lastLogin: '2025-03-01T08:00:00Z',
    createdAt: '2025-01-10T10:00:00Z',
    preferences: { notifications: true, emailUpdates: true, language: 'en' },
  },
  {
    id: 'usr_002',
    userId: 'USR002',
    name: 'Ramesh Kumar',
    email: 'ramesh@vendor.eduresult',
    phone: '+91-98765-43210',
    role: 'vendor',
    zone: 'vendor',
    isActive: true,
    lastLogin: '2025-03-01T07:30:00Z',
    createdAt: '2024-03-15T10:00:00Z',
    preferences: { notifications: true, emailUpdates: false, language: 'en' },
  },
  {
    id: 'usr_003',
    userId: 'USR003',
    name: 'DPS Admin',
    email: 'admin@dps.delhi.edu',
    phone: '+91-11-2655-0001',
    role: 'school_admin',
    zone: 'school',
    isActive: true,
    lastLogin: '2025-02-28T16:00:00Z',
    createdAt: '2024-06-01T09:00:00Z',
    preferences: { notifications: true, emailUpdates: true, language: 'en' },
  },
  {
    id: 'usr_004',
    userId: 'USR004',
    name: 'Platform Admin',
    email: 'admin@eduresult.pro',
    phone: '+91-11-4000-0000',
    role: 'platform_admin',
    zone: 'admin',
    isActive: true,
    lastLogin: '2025-03-01T06:00:00Z',
    createdAt: '2023-12-01T00:00:00Z',
    preferences: { notifications: true, emailUpdates: true, language: 'en' },
  },
  {
    id: 'usr_005',
    userId: 'USR005',
    name: 'Suresh Gupta',
    email: 'suresh.gupta@yahoo.com',
    phone: '+91-98200-33333',
    role: 'parent',
    zone: 'parent',
    isActive: true,
    lastLogin: '2025-02-28T20:00:00Z',
    createdAt: '2025-01-12T14:30:00Z',
    preferences: { notifications: true, emailUpdates: false, language: 'en' },
  },
  {
    id: 'usr_006',
    userId: 'USR006',
    name: 'Priya Sharma',
    email: 'priya@vendor.eduresult',
    phone: '+91-98765-43212',
    role: 'vendor',
    zone: 'vendor',
    isActive: true,
    lastLogin: '2025-03-01T09:00:00Z',
    createdAt: '2024-01-10T10:00:00Z',
    preferences: { notifications: true, emailUpdates: true, language: 'en' },
  },
  {
    id: 'usr_007',
    userId: 'USR007',
    name: 'Greenwood Admin',
    email: 'admin@greenwoodintl.edu',
    phone: '+91-80-2847-5001',
    role: 'school_admin',
    zone: 'school',
    isActive: true,
    lastLogin: '2025-02-27T14:00:00Z',
    createdAt: '2024-04-01T10:00:00Z',
    preferences: { notifications: true, emailUpdates: true, language: 'en' },
  },
  {
    id: 'usr_008',
    userId: 'USR008',
    name: 'Deepa Reddy',
    email: 'deepa@vendor.eduresult',
    phone: '+91-98765-43214',
    role: 'vendor',
    zone: 'vendor',
    isActive: true,
    lastLogin: '2025-03-01T10:00:00Z',
    createdAt: '2023-11-25T10:00:00Z',
    preferences: { notifications: false, emailUpdates: false, language: 'en' },
  },
];

// ── Gamification Profiles ─────────────────────────────────────────────────────

export const gamificationProfiles: ParentGamification[] = [
  {
    id: 'gp_001',
    parentId: 'usr_001',
    totalXp: 3240,
    currentLevel: 5,
    levelTitle: 'Master Parent',
    nextLevelXp: 4000,
    currentLevelXp: 240,
    badges: [
      { id: 'bdg_001', name: 'Early Bird', description: 'Registered within first month of launch', icon: 'Sunrise', earnedAt: '2025-01-15T10:00:00Z', category: 'early_bird' },
      { id: 'bdg_002', name: 'Bulk Buyer', description: 'Purchased 3+ forms in a single transaction', icon: 'ShoppingCart', earnedAt: '2025-02-10T14:00:00Z', category: 'bulk_buyer' },
      { id: 'bdg_003', name: 'Networker', description: 'Referred 5+ parents to the platform', icon: 'Users', earnedAt: '2025-02-20T09:00:00Z', category: 'networker' },
    ],
    rank: 'gold',
    streakDays: 15,
    referralsCount: 8,
    formsPurchased: 6,
    schoolsApplied: 4,
  },
  {
    id: 'gp_002',
    parentId: 'usr_005',
    totalXp: 1850,
    currentLevel: 3,
    levelTitle: 'Active Parent',
    nextLevelXp: 2000,
    currentLevelXp: 850,
    badges: [
      { id: 'bdg_004', name: 'Trendsetter', description: 'First to apply to a newly joined school', icon: 'TrendingUp', earnedAt: '2025-02-15T11:00:00Z', category: 'trendsetter' },
    ],
    rank: 'silver',
    streakDays: 7,
    referralsCount: 2,
    formsPurchased: 3,
    schoolsApplied: 2,
  },
  {
    id: 'gp_003',
    parentId: 'stu_003',
    totalXp: 920,
    currentLevel: 2,
    levelTitle: 'New Explorer',
    nextLevelXp: 1000,
    currentLevelXp: 920,
    badges: [
      { id: 'bdg_005', name: 'First Step', description: 'Completed first application', icon: 'Footprints', earnedAt: '2025-02-11T12:00:00Z', category: 'milestone' },
    ],
    rank: 'bronze',
    streakDays: 3,
    referralsCount: 0,
    formsPurchased: 2,
    schoolsApplied: 1,
  },
];

// ── Notifications ─────────────────────────────────────────────────────────────

export const notifications: Notification[] = [
  {
    id: 'notif_001',
    userId: 'usr_001',
    type: 'success',
    title: 'Interview Scheduled',
    message: 'Your interview at Delhi Public School is scheduled for March 15, 2025 at 9:00 AM.',
    read: false,
    actionUrl: '/parent/tickets',
    createdAt: '2025-02-10T14:05:00Z',
  },
  {
    id: 'notif_002',
    userId: 'usr_001',
    type: 'info',
    title: 'Document Verified',
    message: 'Your Birth Certificate has been verified and blockchain-anchored.',
    read: true,
    actionUrl: '/parent/documents',
    createdAt: '2025-01-16T08:30:00Z',
  },
  {
    id: 'notif_003',
    userId: 'usr_001',
    type: 'warning',
    title: 'Application Waitlisted',
    message: 'Your application to DPS is waitlisted #23. Seat availability will be updated.',
    read: false,
    actionUrl: '/parent/dashboard',
    createdAt: '2025-02-26T09:00:00Z',
  },
  {
    id: 'notif_004',
    userId: 'usr_002',
    type: 'success',
    title: 'Payment Received',
    message: 'Rs. 500 received from Rajesh Sharma for DPS Admission. 5 tokens deducted.',
    read: false,
    actionUrl: '/vendor/dashboard',
    createdAt: '2025-02-10T14:01:00Z',
  },
  {
    id: 'notif_005',
    userId: 'usr_002',
    type: 'info',
    title: 'Commission Credited',
    message: 'Weekly commission of Rs. 250 has been credited to your account.',
    read: true,
    actionUrl: '/vendor/payments',
    createdAt: '2025-02-24T10:05:00Z',
  },
  {
    id: 'notif_006',
    userId: 'usr_003',
    type: 'success',
    title: 'New Applicant',
    message: 'New application received from Aarav Sharma (Class 1).',
    read: false,
    actionUrl: '/school/applicants',
    createdAt: '2025-02-10T10:00:00Z',
  },
  {
    id: 'notif_007',
    userId: 'usr_004',
    type: 'warning',
    title: 'Vendor Alert',
    message: 'Vendor VEN004 (Amit Singh) performance score dropped below threshold.',
    read: false,
    actionUrl: '/admin/vendors',
    createdAt: '2025-02-28T09:00:00Z',
  },
  {
    id: 'notif_008',
    userId: 'usr_001',
    type: 'success',
    title: 'Badge Earned!',
    message: 'Congratulations! You earned the "Networker" badge for 5+ referrals.',
    read: false,
    actionUrl: '/parent/dashboard',
    createdAt: '2025-02-20T09:05:00Z',
  },
];

// ── Academic Years ────────────────────────────────────────────────────────────

export const academicYears: AcademicYear[] = [
  {
    id: 'ay_001',
    year: '2024-25',
    startDate: '2024-04-01',
    endDate: '2025-03-31',
    isActive: false,
    admissionOpenDate: '2024-01-01',
    admissionCloseDate: '2024-03-31',
    description: 'Current academic year',
  },
  {
    id: 'ay_002',
    year: '2025-26',
    startDate: '2025-04-01',
    endDate: '2026-03-31',
    isActive: true,
    admissionOpenDate: '2025-01-01',
    admissionCloseDate: '2025-03-31',
    description: 'Active admission year',
  },
  {
    id: 'ay_003',
    year: '2026-27',
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    isActive: false,
    admissionOpenDate: '2026-01-01',
    admissionCloseDate: '2026-03-31',
    description: 'Upcoming academic year',
  },
];

// ── Grading Scales ────────────────────────────────────────────────────────────

export const gradingScales: GradingScale[] = [
  { id: 'grade_001', grade: 'A+', minPercentage: 90, maxPercentage: 100, gradePoint: 10, description: 'Outstanding' },
  { id: 'grade_002', grade: 'A', minPercentage: 80, maxPercentage: 89, gradePoint: 9, description: 'Excellent' },
  { id: 'grade_003', grade: 'B+', minPercentage: 70, maxPercentage: 79, gradePoint: 8, description: 'Very Good' },
  { id: 'grade_004', grade: 'B', minPercentage: 60, maxPercentage: 69, gradePoint: 7, description: 'Good' },
  { id: 'grade_005', grade: 'C', minPercentage: 50, maxPercentage: 59, gradePoint: 6, description: 'Average' },
  { id: 'grade_006', grade: 'D', minPercentage: 40, maxPercentage: 49, gradePoint: 5, description: 'Below Average' },
  { id: 'grade_007', grade: 'F', minPercentage: 0, maxPercentage: 39, gradePoint: 0, description: 'Fail' },
];

// ── Helper Functions ──────────────────────────────────────────────────────────

export function getSchoolById(id: string): School | undefined {
  return schools.find((s) => s.id === id);
}

export function getApplicationsByStudent(studentId: string): Application[] {
  return applications.filter((a) => a.studentId === studentId);
}

export function getTicketsByStudent(studentId: string): InterviewTicket[] {
  return interviewTickets.filter((t) => t.studentId === studentId);
}

export function getDocumentsByStudent(studentId: string): VaultDocument[] {
  return vaultDocuments.filter((d) => d.studentId === studentId);
}

export function getVendorById(id: string): Vendor | undefined {
  return vendors.find((v) => v.id === id);
}

export function getTransactionsBySchool(schoolId: string): Transaction[] {
  return transactions.filter((t) => t.schoolId === schoolId);
}

export function calculateMatchScore(
  _student: StudentProfile,
  _school: School
): number {
  const baseScore = Math.floor(Math.random() * 40) + 60;
  const boardBonus = Math.random() > 0.5 ? 10 : 0;
  const locationBonus = Math.random() > 0.5 ? 15 : 5;
  const demandPenalty =
    _school.demandLevel === 'critical'
      ? -10
      : _school.demandLevel === 'high'
        ? -5
        : 0;
  return Math.min(100, Math.max(0, baseScore + boardBonus + locationBonus + demandPenalty));
}

export function calculateFormPrice(form: FormCatalogItem, quantity: number): number {
  const baseTotal = form.demandAdjustedPrice * quantity;
  if (form.bulkDiscountThreshold > 0 && quantity >= form.bulkDiscountThreshold) {
    const discount = (baseTotal * form.bulkDiscountPercent) / 100;
    return baseTotal - discount;
  }
  return baseTotal;
}
